[package]
name = "tucant-api"
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
axum = { version = "0.8.1", features = ["macros"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
utoipa = { git = "https://github.com/juhaku/utoipa.git" }
serde = { version = "1.0", features = ["derive"] }
utoipa-swagger-ui = { git = "https://github.com/juhaku/utoipa.git", features = ["axum", "vendored"] }
tucan-connector = { path = "../tucan-connector" }
utoipa-axum = { git = "https://github.com/juhaku/utoipa.git" }
tucant-types = { path = "../tucant-types" }
axum-extra = { version = "0.10.0", features = ["cookie"]}
serde_json = "1.0.133"

[lints]
workspace = true
