[package]
name = "cddl-codegen"
license.workspace = true
edition.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1.0.97"
heck = "0.5.0"
prettyplease = "0.2.32"
proc-macro2 = "1.0.94"
quote = "1.0.40"
syn = "2.0.100"
winnow = "0.7.6"

[lints]
workspace = true
