trunk-version = "^0.21.6"

[build]
target = "./index.html"
minify = "never"

[watch]
watch = ["../../tucant-extension", "../tucant-yew", "../tucan-connector", "../tucant-types", "../tucant-api/src", "../tucant-api/Cargo.toml", "../key-value-database"]
ignore = ["../../tucant-extension/dist", "../tucant-yew/dist"]

[serve]
port = 1420
open = false

[[proxy]]
backend = "http://localhost:3000/api"

[[hooks]]
stage = "post_build"  # When to run hook, must be one of "pre_build", "build", "post_build"
command = "bash"        # Command to run
command_arguments = ["./fixup.sh"] # Arguments to pass to command