[package]
name = "tucant-types"
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
utoipa = "5"
axum-core = "0.5.0"
thiserror = "2"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "http2", "charset", "stream"] }
regex = { version = "1" }
itertools = "0.14"
dynosaur = "0.3"

[lints]
workspace = true
