[package]
name = "tucant-leptos"
license.workspace = true
edition.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.8.2", features = ["csr"] }
console_log = { version = "1", features = ["color"] }
log = "0.4.27"
tucant-types = { path = "../tucant-types" }
leptos_router = "0.8.2"
reqwest = { version = "0.12.9", default-features = false, features = ["rustls-tls", "http2", "charset", "json"] }
url = "2"
serde_json = "1"

[lints]
workspace = true
