[package]
name = "tucant-leptos"
license.workspace = true
edition.workspace = true
version.workspace = true
rust-version.workspace = true

[features]
tauri = []
direct = ["dep:tucan-connector", "dep:web-extensions-sys"]
api = []

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { git = "https://github.com/mohe2015/leptos.git", branch = "add-hash-router", features = ["csr"] }
leptos_router = { git = "https://github.com/mohe2015/leptos.git", branch = "add-hash-router" }
console_log = { version = "1", features = ["color"] }
log = "0.4.27"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
tucant-types = { path = "../tucant-types" }
reqwest = { version = "0.12.9", default-features = false, features = ["rustls-tls", "http2", "charset", "json"] }
url = "2"
serde_json = "1"
tucan-connector = { optional = true, path = "../tucan-connector" }
web-extensions-sys = { optional = true, git = "https://github.com/mohe2015/web-extensions-sys", branch = "cookies" }
web-sys = { version = "0.3", features = ["Document", "Window", "HtmlDocument", "NodeList", "HtmlSelectElement"] }
cookie = "0.18"
js-sys = "0.3"
serde-wasm-bindgen = "0.6"

[lints]
workspace = true
