trunk-version = "^0.21.6"

[build]
target = "./index.html"

# https://github.com/trunk-rs/trunk/issues/288#issuecomment-2888905513
inject_scripts = false
filehash = false

minify = "never"

[watch]
watch = ["../../tucant-extension", "../tucant-leptos", "../tucan-connector", "../tucant-types", "../tucant-api/src", "../tucant-api/Cargo.toml", "../key-value-database"]
ignore = ["../../tucant-extension/dist", "../tucant-leptos/dist"]

[serve]
port = 1420
open = false

[[proxy]]
backend = "http://localhost:3000/api"
