[package]
name = "tucant-tests-webdriver-bidi"
license.workspace = true
edition.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
webdriverbidi = { git = "https://github.com/TahaHachana/webdriverbidi.git" }
tokio = { features = ["full"], version = "1" }
anyhow = "1.0.97"

[lints]
workspace = true
