[application]
name = "tucan-plus"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "TUCaN Plus"

[[web.proxy]]
backend = "http://127.0.0.1:3000/api/"

# https://developer.android.com/build/building-cmdline
# keytool -genkey -v -keystore my-release-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias my-alias
# dx bundle --platform android --release
[bundle.android]
jks_file = "../my-release-key.jks"
jks_password = "password"
key_alias = "my-alias"
key_password = "password"

[web.watcher]
reload_html = true
watch_path = ["src", "public"]

[web.resource]
style = ["./assets/bootstrap.css"]

[web.resource.dev]

