[package]
name = "tucant-tests"
license.workspace = true
edition.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
# webdriverbidi = { path = "../../../webdriverbidi" }
webdriverbidi = { git = "https://github.com/mohe2015/webdriverbidi.git", branch = "main" }
tokio = { features = ["full"], version = "1" }
anyhow = "1.0.97"
env_logger = "0.11.8"
serde_json = "1.0.140"
serde = "1.0.219"
dotenvy = "0.15.7"

[lints]
workspace = true
