[unstable]
build-std = ["std", "panic_unwind"]

[build]
target = "wasm32-unknown-unknown"
rustflags = ["-C", "panic=unwind", "--cfg=web_sys_unstable_apis", "--cfg=getrandom_backend=\"wasm_js\""]

[profile.release]
panic = "unwind"