[package]
name = "key-value-database"
license = "AGPL-3.0-or-later"
edition = "2024"
version = "0.1.2"
rust-version = "1.85.1"

[dependencies]
indexed-db = "0.4"
js-sys = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-wasm-bindgen = "0.6"
futures-util = { version = "0.3", features = ["io"] }
tempfile = "3.19.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
send_wrapper = "0.6.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
sqlx = { version = "0.8", default-features = false, features = [ "runtime-tokio", "sqlite", "derive" ] }
tokio = { version = "1", features = ["fs"] }
