[package]
name = "key-value-database"
license.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
indexed-db = "0.4"
js-sys = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-wasm-bindgen = "0.6"
futures-util = { version = "0.3", features = ["io"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
sqlx = { version = "0.8", default-features = false, features = [ "runtime-tokio", "sqlite", "derive" ] }
tokio = { version = "1.42.0", features = ["fs"] }

[lints]
workspace = true
