[package]
name = "tucant-dioxus"
version = "0.1.0"
authors = ["Moritz Hedtke <Moritz.Hedtke@t-online.de>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { git = "https://github.com/mohe2015/dioxus.git", branch = "hash-history", features = ["router"] }
tucant-types = { path = "../tucant-types" }
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }
reqwest = { version = "0.12.9", default-features = false, features = ["rustls-tls", "http2", "charset", "json"] }
wasm-bindgen-futures = "0.4"

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
