name: Rust

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-26.04
    steps:
    - uses: actions/checkout@v6
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v17
      with:
        name: tucan-plus
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: |
          nix build -L .#extension-unpacked
    - uses: actions/upload-artifact@v7
      with:
        name: tucan-plus-extension-nightly-zip
        path: result/